### ISSUE TITLE
Resolve getenv everywhere?

### ISSUE THREAD

**Issue by psarka** [intake/intake#257]
I was setting up gcloud authentication tokens following [this](https://github.com/ContinuumIO/intake/issues/195#issuecomment-437504787) and thought, why are `getenv`s limited to default field for the parameters? If there were expanded everywhere, I could setup the tokens easier:

```
sources:
  gcs_csv:
    description: "CSV data on GCS; requires gcsfs and a token"
    args:
      urlpath: gcs://private_bucket/path/*.csv
      storage_options:
        token: "getenv(GOOGLE_APPLICATION_CREDENTIALS)"
```

Does more broad expansion of `getenv` have some drawbacks?
