### ISSUE TITLE
Parameter name uniqueness enforced globally on catalog.yml

### ISSUE THREAD

**Issue by gbrener** [intake/intake#28]
The following catalog.yml (or a similar one) raises a ValidationError with "name already exists" due to the parameter names being the same:

```
...
sources:

  - name: sample1
    parameters:
        - name: a
          ...

  - name: sample2
    parameters:
        - name: a
          ...
```

It appears that we're enforcing name uniqueness on parameter names globally (across all data sources in catalog.yml files), rather than locally to each data source. If that is intentional, it might make sense for us to change the schema so that "parameters" is no longer nested underneath each data source - this would make the global namespacing clearer. If not desired, then it's likely the indication of a bug in the _marshmallow_ schema validation code. We could also do a combination of the two approaches - having one global parameters section and an optional parameters list on each local source.
