### ISSUE TITLE
Unable to ignore items when loading a compressed file

### ISSUE THREAD

**Issue by gramhagen** [intake/intake#289]
I created a yaml spec pointing to a compressed file online, however there are additional (e.g. readme) files included in the tarball that confuse the data loader, which as far as I can understand tries to load all the decompressed files as dataframes.

I've tested a small code change that modifies the cache spec to include a regex_filter parameter which can be used to filter the desired item(s) from the compressed file. This seems like a pretty common scenario to support. Let me know if there's already an easier way to do this, Otherwise my suggestion is to have something like this:

```
sources:
  test:
    driver: csv
    args:
      urlpath: test.tar.gz
    cache:
      - type: compressed
        argkey: urlpath
        regex_filter: '.*sample.txt'
```
