### ISSUE TITLE
YAMLFilesCatalog not working with remote path

### ISSUE THREAD

**Issue by rafa-guedes** [intake/intake#411]
I am trying to organise some intake catalog with some master config pointing to folders containing multiple configs. I'm using the `YAMLFilesCatalog` driver for that. This is working fine when the configs are in my local machine, but not when they are in a bucket.

I have some dummy setup to demonstrate this issue. The two configs (pasted at the bottom here) are in the bucket specified below, this should be able to be reproduced.

**Source *`fromfolder`* defines a sub-catalog in master pointing to a folder via `YAMLFilesCatalog`.**
```python
import intake

# Using local configs
cat = intake.Catalog("path/to/master-catalog.yml")
cat.fromfolder.some_dataset.to_dask() # works

# Using remote configs
cat = intake.Catalog("gs://my-intake/master-catalog.yml")
cat.fromfolder.some_dataset.to_dask() # fails

2019-09-04 17:17:36,031 - intake - INFO - local.py:_load:L764 - Loading "name: child-catalog
container: catalog
plugin: ['yaml_file_cat']
description: YAML file: child-catalog
direct_access: True
user_parameters: []
metadata: 
  catalog_dir: gs://my-intake
args: 
  name: gs://my-intake/folder/*
  ttl: 1
  path: my-intake/folder/child-catalog.yml" as a catalog failed: [Errno 2] No such file or directory: '/home/rguedes/my-intake/folder/child-catalog.yml'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
```
When using YAMLFilesCatalog, `{{CATALOG_DIR}}` seems to be evaluating to the local directory in my computer instead of the remote path.

This approach works both in my local machine and in the bucket if I point to the child config directly using `YAMLFileCatalog` instead of `YAMLFilesCatalog`.

**Source *`fromfile`* defines a sub-catalog in master pointing to a folder via `YAMLFileCatalog`.**

```python
import intake

# Using local configs
cat = intake.Catalog("path/to/master-catalog.yml")
cat.fromfile.some_dataset.to_dask() # works

# Using remote configs
cat = intake.Catalog("gs://my-intake/master-catalog.yml")
cat.fromfile.some_dataset.to_dask() # works
```

## Master config

**./master-catalog.yml**
```
metadata:
  version: 1

description: Master catalog

sources:

  fromfile:
    description: Sub-catalog from single remote file
    driver: intake.catalog.local.YAMLFileCatalog
    args:
      path: "{{CATALOG_DIR}}/folder/child-catalog.yml"
    metadata: {}

  fromfolder:
    description: Sub-catalog from files in remote path
    driver: intake.catalog.local.YAMLFilesCatalog
    args:
      path: "{{CATALOG_DIR}}/folder"
    metadata: {}
```

**./folder/child-catalog.yml**
```
metadata:
  version: 1

sources:

  some_dataset:
    description: Some dataset.
    metadata:
      tags:
        - tag1
        - tag2
    driver: intake_xarray.xzarr.ZarrSource
    args:
      urlpath: gs://my-intake/some_dataset.zarr
      storage_options:
        token: anon
      consolidated: True

```
