### ISSUE TITLE
How can i use library intake to create one catalog.yaml file to reference nested directories?

### ISSUE THREAD

**Issue by an5ir** [intake/intake#425]
I have the following nested directories: 
```
\---population
    +---asia
    |   |   asia_pop.xlsx
    |   |   
    |   +---china
    |   |       china_pop.xlsx
    |   |       
    |   \---japan
    |           japan_pop.xlsx
    |           
    \---europe
        |   europe_total_pop.xlsx
        |   
        +---france
        |       france_pop.xlsx
        |       
        \---uk
                uk_pop.xlsx
```

Is there anyway to create one catalog.yaml file that can work it way through the directories in the following manner? 
```
Import intake
root = intake.open_catalog(‘/population/population.yaml’)

# load china population

root.asia.china.read()
```
I know it is possible by nesting multiple catalog.yaml file but is there any way of doing it in one file.

For example:
```
metadata:
  version:1
  
sources:
  asia:
    china:
      driver: csv
      args:
        url:'/population/asia/china/china_pop.xlsx'
      metadata: {}

    japan:
      driver: csv
      args:
        url:'/population/asia/japan/japan_pop.xlsx'
      metadata: {}
```

**Comment by martindurant** [comment]
@talebzeghmi , perhaps zillow/dal's catalog type would be appropriate here?

Short answer, you can indeed have nested yaml files, or you can refer to the set of data sources from a single catalog file too. Also, there are several catalog driver types that deal with walking structured sets of directories, but I don't think one quite specific to automatically generating what you want here.

**Comment by an5ir** [comment]
thanks for the replay 
i'm not sure what exactly i'm looking for in terms of driver.
can you give me any example of driver that at deal with walking structured sets of directories?

is it possible for one data source to reference another data-source in the same yaml file?
i.e Asia reference china which reference the excel file 

if so can you share an example?

**Comment by martindurant** [comment]
Yes, but its far from simple: https://github.com/NCAR/intake-esm/blob/master/intake_esm/cmip.py

A "catalog driver" is something that inherits from `intake.catalog.Catalog`, and is usually far simpler than this.

For your situation, you could come up with something short, but the question is, how specific do you want it to be to your situation? The obvious alternative is to write a little script to `os.walk` through the directory and create either  set of catalogs which reference each other, or use https://github.com/zillow/intake-nested-yaml-catalog to make an on-one nested catalog. 

Note that if you want just the nice naming, then a simple catalog would do, e.g.:
```yaml
sources:
  asia.china: 
    ...
  asia.india:
    ...
```
is totally fine, except that you would reference the datasets as `cat['asia.china']` instead of using attribute lookup. Tab completion in the square brackets selector should still work.

**Comment by talebzeghmi** [comment]
If using https://github.com/zillow/intake-nested-yaml-catalog then you can define it as such getting free tab completion and the Intake Gui.

![image](https://user-images.githubusercontent.com/4167032/66945177-7204dc00-f003-11e9-8ebe-6196a1776a6b.png)

```yaml
metadata:
  hierarchical_catalog: true
population:
  asia:
    china:
      driver: csv
      args:
        url: '/population/asia/china/china_pop.csv'
      metadata: {}
    japan:
      driver: csv
      args:
        url: '/population/asia/japan/japan_pop.csv'
      metadata: {}
  europe:
    france:
      driver: csv
      args:
        url: '/population/europe/france/france_pop.csv'
      metadata: {}
```
