### ISSUE TITLE
Key-value pair for source parameter in catalog

### ISSUE THREAD

**Issue by hoangthienan95** [intake/intake#435]
When creating a catalog, alot of the times I don't want to use simple templating for source's parameters in the catalog, but a mapping of what is exposed to user and the underlying value. Is there an easy way to do this?

For example:
```
sources:
  SEP_pairs_results:
    parameters: # User parameters
      experiment: #experiment type, shared parameter
         allowed: ["exp_1", "exp_2"]

      data_type:
        description: data
        type: str
        default: "output"
        allowed: ["input", "output"]

       trial_num: # Need this to be allowed only if user selected "output" as data_type
          description: trial number
          type: int
          allowed: [1,2,3....20]
         
    args:
      csv_kwargs:
        include_path_column: True
        sep: "\t"
      urlpath:  #different paths based on data_type parameter
        input: "input/folder/path/input_{{experiment}}"
        output: "output/folder/path/{{experiment}}_output_{{trial_num}}"
```
From what I understand, the current scheme supports templating that go from a very general file path template and then split into smaller branches based on templating parameters. However, it is not possible to build a "parallel" branch or completely different branches. 

I'm trying to do some bookeeping, gathering input, output, analyses on output of the same experiment in the same catalog which requires me to pull things from different paths and/or different naming conventions
