### ISSUE TITLE
Intake Cache specify filename/location

### ISSUE THREAD

**Issue by pgierz** [intake/intake#481]
Also posted on SO: https://stackoverflow.com/questions/60773855/intake-cache-specify-filename-location

Hello,

I'm trying to use `intake` and the `intake-xarray` to open and store remote files. I have a minimized catalog file here:

`/isibhv/projects/paleo_pool/boundary_conditions/ice_sheet_reconstructions/ice_sheet_reconstructions.yaml`

It looks like this:

```yaml
metadata:
  version: 1
sources:
  glac1d:
    description: The GLAC-1D Reconstruction 
    driver: netcdf
    args:
        urlpath: "https://sharebox.lsce.ipsl.fr/index.php/s/yfuUw91ruuJXroC/download?path=%2F&files=TOPicemsk.GLACD26kN9894GE90227A6005GGrBgic.nc"
    cache_dir: "{{ CATALOG_DIR }}/glac1d"
    cache: 
        - argkey: urlpath
          type: file
```

I can open the files in Python:

```python
import intake
cat = intake.open_catalog("ice_sheet_reconstructions.yaml")
ds = cat.glac1d.read()
```

This all works wonderfully; and I get the file as I would expect it. However, the cache doesn't show up where I would expect. I would have guessed a new folder is made under:

```
/isibhv/projects/paleo_pool/boundary_conditions/ice_sheet_reconstructions/glac1d
```

Instead, I get something in my home directory.

Did I specify the cache directory incorrectly?

As a second question: is it possible to directly specify how the cached files should be called when they are saved?

Thanks!
Paul

**Comment by weiji14** [comment]
It took me a while, but after looking at the [test case example](https://github.com/martindurant/intake-xarray/blob/16066590843112ecaf5c83c8cda61beb6cea2731/intake_xarray/tests/test_intake_xarray.py#L349-L361) in #62 and reading https://intake.readthedocs.io/en/latest/catalog.html#caching and https://filesystem-spec.readthedocs.io/en/latest/features.html#caching-files-locally very closely, I think I've figured it out! The YAML should look something like this:

```yaml
metadata:
  version: 1
sources:
  glac1d:
    args:
      urlpath: simplecache::https://somewhere.org/data_filename.nc
      storage_options:
        simplecache:
          cache_storage: glac1d
          same_names: True
```

`cache_storage` is the directory where the file(s) will go into, in this case 'glac1d' in the current folder. Using `same_names=True` ([default is False](https://github.com/intake/filesystem_spec/blob/de54f06c08989e902e1703621ed99b15feac4085/fsspec/implementations/cached.py#L47)) will make sure the cached filename is 'data_filename.nc' instead of some arbitrary hash.

Note that this relies on installing an unreleased version of https://github.com/intake/intake-xarray/commit/f4e6211d5c402256cd1036a5f490ae9a00a61832. And maybe the latest version of fsspec (0.7.3?) and intake (0.5.5?) too.

Now I just need to figure out how to parallelize file downloads via fsspec for my own use case. The [old intake cache method](https://intake.readthedocs.io/en/latest/catalog.html#caching-source-files-locally) automagically allowed for simultaneous downloads via dask, but it seems to be deprecated. That's for a separate topic though.
