### ISSUE TITLE
Use Metadata for 

### ISSUE THREAD

**Issue by pgierz** [intake/intake#485]
Hello,

I was wondering if it were possible to use the metadata section of a catalog for the "allowed" section of sources? I have something like this:

```yaml
metadata:
        version: 2
        basedir: /work/ollie/pgierz/PISM
        experiments:
                - pindex_vostok_stop0_cthk200.0
                - pindex_vostok_stop30_cthk200.0
                - pindex_vostok_stop40_cthk200.0
                - pindex_vostok_stop50_cthk200.0
                - pindex_vostok_ds30
                - pindex_vostok_ds40
                - pindex_vostok_ds50
        experiment_labels:
                pindex_vostok_stop0_cthk200.0: "Standard Index Run"
                pindex_vostok_stop30_cthk200.0: "Constant Forcing: 30 ka"
                pindex_vostok_stop40_cthk200.0: "Constant Forcing: 40 ka"
                pindex_vostok_stop50_cthk200.0: "Constant Forcing: 50 ka"
                pindex_vostok_ds30: "Downscaling Active: 30 ka"
                pindex_vostok_ds40: "Downscaling Active: 40 ka"
                pindex_vostok_ds50: "Downscaling Active: 50 ka"
        experiment_colors:
                pindex_vostok_stop0_cthk200.0: "black"
        

sources:
  full_experiment:
    args:
      urlpath: "/work/ollie/pgierz/PISM/{{ expid }}/outdata/pism/{{ expid }}_pismr_{{ filetype }}_*nc"
      concat_dim: "time"
      xarray_kwargs:
          combine: "by_coords"
    parameters:
        expid:
          description: Which experiment to load
          type: str
          allowed:
                - pindex_vostok_stop0_cthk200.0
                - pindex_vostok_stop30_cthk200.0
                - pindex_vostok_stop40_cthk200.0
                - pindex_vostok_stop50_cthk200.0
                - pindex_vostok_ds30
                - pindex_vostok_ds40
                - pindex_vostok_ds50
        filetype:
          description: Which files to load (extra or timeseries)
          type: str
          allowed:
                - extra
                - timeseries
    description: ''
    driver: intake_pism.pism.PismSource
    metadata: {}
    
  LGM_snapshot:
    args:
      urlpath: "/work/ollie/pgierz/PISM/{{ expid }}/outdata/pism/{{ expid }}_pismr_extra_-021000--020001.nc"
    parameters:
        expid:
          description: Which experiment to load
          type: str
          allowed:
                - pindex_vostok_stop0_cthk200.0
                - pindex_vostok_stop30_cthk200.0
                - pindex_vostok_stop40_cthk200.0
                - pindex_vostok_stop50_cthk200.0
                - pindex_vostok_ds30
                - pindex_vostok_ds40
                - pindex_vostok_ds50
    description: ''
    driver: intake_pism.pism.PismSource
    metadata: {}
    
  newest_files:
    args:
      urlpath: "/work/ollie/pgierz/PISM/{{ expid }}/outdata/pism/latest_{{ filetype }}_file_pism.nc"
    parameters:
        expid:
          description: Which experiment to load
          type: str
          allowed:
                - pindex_vostok_stop0_cthk200.0
                - pindex_vostok_stop30_cthk200.0
                - pindex_vostok_stop40_cthk200.0
                - pindex_vostok_stop50_cthk200.0
                - pindex_vostok_ds30
                - pindex_vostok_ds40
                - pindex_vostok_ds50
        filetype:
          description: Which files to load (extra or timeseries)
          type: str
          allowed:
                - ex
                - ts
    description: ''
    driver: intake_pism.pism.PismSource
    metadata: {}
```

It'd be nice to reduce the duplicate information and just reference the metadata in the various source blocks. Is that possible? Maybe I overlooked something in the documentation....
