### ISSUE TITLE
Caching for multiple entries based on the same tar archive is broken

### ISSUE THREAD

**Issue by willirath** [intake/intake#500]
For tar archive with multiple CSV files and a catalog that has one entry per CSV file but (loaded with `cache`, see below), `.read()` only returns data from the first entry that was loaded.

### Demonstration

Setting up the tar archive:
```shell
$ rm -rf ~/.intake/
$ mkdir -p two_csvs/
$ seq 0 9 | paste -sd, > two_csvs/data_01.csv
$ seq 20 40 | paste -sd, > two_csvs/data_02.csv
$ tar -czf two_csvs.tar.gz two_csvs/
$ cat two_csvs/data_01.csv
0,1,2,3,4,5,6,7,8,9
$ cat two_csvs/data_02.csv
20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40
```

Catalog file `catalog.yaml`:
```yaml
metadata:
  version: 1

sources:
  data_01:
    driver: csv
    args:
      urlpath: "two_csvs.tar.gz"
    cache:
      - type: compressed
        decomp: tgz
        argkey: urlpath
        regex_filter: 'data_01.csv'
            
  data_02:
    driver: csv
    args:
      urlpath: "two_csvs.tar.gz"
    cache:
      - type: compressed
        decomp: tgz
        argkey: urlpath
        regex_filter: 'data_02.csv'
```

Load catalog:
```python
import intake
cat = intake.open_catalog("catalog.yaml")
```

Reading first file gives expected result:
```
print(list(cat["data_01"].read()))  # truth: 0..9
```
```
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
```

Reading second file gives data of first file instead:
```python
print(list(cat["data_02"].read()))  # truth: 20..40
```
```
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
```

Clearing cache and reading second file gives expected result:
```python
cat["data_02"].cache[0].clear_all()
print(list(cat["data_02"].read()))  # truth: 20..40
```
```
['20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40']
```

But then, first entry is wrong:
```python
print(list(cat["data_01"].read()))  # truth: 0..9
```
```
['20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40']
```
