### ISSUE TITLE
Templating nested YAML catalogues

### ISSUE THREAD

**Issue by ScottWales** [intake/intake#511]
I have a nested data structure, where the same structure is repeated for different experiment runs
```
run1
    - aa
        - x.nc
        - y.nc
    - bb
        - z.nc
run2
    - aa
        - x.nc
        - y.nc
    - bb
        - z.nc
...
```
I'd like to access the data like `catalog.run1.aa.x`, so it looks like I should use nested YAML catalogues, however I'd prefer not to make a catalogue file for every run directory, as this would have a lot of repeated information.

Templates look like a possible solution to this, however I can't see a way to pass a template parameter from one level of the nest to the next. Something like
```
# catalog_top.yaml
sources:
    run1:
        driver: intake.catalog.local.YAMLFileCatalog
        args:
            path: catalog_mid.yaml
            parameters:
                top_dir: run1

# catalog_mid.yaml
sources:
    aa:
        driver: intake.catalog.local.YAMLFileCatalog
        args:
            path: catalog_mid.yaml
            parameters:
                mid_dir: {{top_dir}}/aa
```
so that the one 'catalog_mid.yaml' file will work for each experiment directory, each with a different `top_dir`.

Does something like this already exist?
