### ISSUE TITLE
cannot specify projection for plot

### ISSUE THREAD

**Issue by Chilipp** [intake/intake#532]
Hey lovely intake developers,

I really appreciate your work on this package and it's a wonderful resource for data managers to make their output more accessible!!

I do have one issue that I want to provide a data-package derived from netCDF-files of a regional climate model using `intake-xarray`, plus some plotting routines using the `plot` section in the catalog. My data is using a rotated pole projection which is straight-forward to plot using cartopys [RotatedPole](https://scitools.org.uk/cartopy/docs/latest/crs/projections.html#rotatedpole) projection. Also geoviews supports this, when I am using something like

```python
import cartopy.crs as ccrs
ds.hvplot.quadmesh(projection=ccrs.RotatePole(...), ...)
```

however, I could not find how to specify this projection in the `yaml` plot section of the catalog, i.e. I'd need something like

```yaml
      plots:
        map:
          kind: quadmesh
          coastline: true
          projection: 
            class: RotatedPole
            pole_longitude: ...
            pole_latitude: ...
```

One possibility would be to include it like

```yaml
projection: !!python/object/apply:cartopy.crs.RotatedPole []
```

which would be valid YAML-Syntax, but intake is using `yaml.safe_load` (see [here](https://github.com/intake/intake/blob/master/intake/utils.py#L78)) and as such prevents loading something like this.

I am not sure, whether `intake` is the correct library where this should be resolved, or whether `geoviews` should allow a different way of specifying the projection. What do you think?
