### ISSUE TITLE
[Feature Request] Support default environment variables in catalog templating

### ISSUE THREAD

**Issue by jhamman** [intake/intake#537]
Suppose I have a catalog that looks like this:

```yaml
sources:
  mysource:
    description: This source needs a prefix environment variable
    args:
      url: "{{ env(MY_PREFIX) }}/data.csv"
```

This requires the `MY_PREFIX` be set by the user for data access to work as designed. Moreover, it results in an unexpected error (something like `FileNotFoundError("'/data.csv' not found")`)  that doesn't tell the user they should have provided an environment variable.

I'm curious if it would be possible to, somewhere in the Catalog, tell intake what to do when  `MY_PREFIX` is not set. In my use case, I would prefer being able to specify a default value but a more informative error would also do.

Something like:

```yaml
env:
  default:
    MY_PREFIX: 'https://example.com'
  # or
  required: [MY_PREFIX, MY_OTHER_PREFIX]

sources:
  ...
```

This syntax would allow intake to a) use default variables when they are not set and/or provide meaningful errors when required variables are not set. Thoughts?
