### ISSUE TITLE
config for caching via fsspec and disable caching

### ISSUE THREAD

**Issue by aaronspring** [intake/intake#551]
**Goal:** I want to switch between caching (with simplecache) by default (when interactively working with a catalog) and not caching by default (e.g. in testing whether sources are available).

```yaml
# atmosphere.yml
plugins:
  source:
    - module: intake_xarray

sources:
  HadCRUT4:
    description: HadCRUT temperature anomalies wrt. 1960-1989
    driver: netcdf
    args:
      urlpath: simplecache::https://crudata.uea.ac.uk/cru/data/temperature/HadCRUT.4.6.0.0.median.nc
      chunks: {'time': 'auto'}
      storage_options:
        simplecache:
          cache_storage: HadCRUT4
          same_names: True
```
EDIT: this item wouldnt work without `simplecache`, however the feature request remains the same.

```python
# how I envision this
import intake
import os
for caching_enabled in [True, False]:
  intake.config.conf['caching_enabled']=caching_enabled
  # fsspec.config.conf['caching_enabled']=caching_enabled
  ds = intake.open_catalog('atmosphere.yml')['HadCRUT4'].to_dask()
  assert (os.path.exists('HadCRUT4') is caching_enabled)
```

**What I found**: `intake` has a `config.conf` to specify defaults for caching, but I think this still concerns the old caching.
```python
intake.config.conf
{'auth': {'cls': 'intake.auth.base.BaseAuth'},
 'port': 5000,
 'cache_dir': '/Users/aaron.spring/.intake/cache',
 'cache_disabled': False,
 'cache_download_progress': True,
 'logging': 'INFO',
 'catalog_path': [],
 'persist_path': '/Users/aaron.spring/.intake/persisted'}
```

**Wishing for**: Implement `caching_disabled` in `config` for `fsspec` or `intake` to disable caching regardless of having `simplecache` in `url`.

I want to use this with `intake-xarray`, but the solution seems to be either in `fsspec` or `intake`.

Along the same line of thought, I would like to set a default base path for all cached files other than setting `cache_storage` by hand for each item. Can this be done for the whole catalog?
