### ISSUE TITLE
Creating ESM source for Intake-esm entries

### ISSUE THREAD

**Issue by charlesbluca** [intake/intake#552]
Currently, there doesn't seem to be any source class for [Intake-esm](https://github.com/intake/intake-esm) collections, meaning that any Intake catalogs containing them must use [`intake_esm.esm_datastore`](https://github.com/intake/intake-esm/blob/ac0f3d1496327039be6748caf554eb4b7ba83a23/intake_esm/core.py#L22) as the driver (seen in [Pangeo's climate catalog](https://github.com/pangeo-data/pangeo-datastore/blob/master/intake-catalogs/climate.yaml))

```yaml
plugins:
  source:
    - module: intake_esm

sources:
  cmip6_gcs:
    args:
      esmcol_obj: "https://storage.googleapis.com/cmip6/pangeo-cmip6.json"
    description: 'CMIP6 in Google Cloud Storage'
    driver: intake_esm.esm_datastore
    metadata: {}
```

This means that accessing these entries directly calls the `intake_esm.esm_datastore` constructor and consequently loads the Intake-esm collection's underlying DataFrame into memory:

```python
In [1]: import intake

In [2]: cat = intake.open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/climate.yaml")

In [3]: cat["cmip6_gcs"]
Out[3]: <pangeo-cmip6 catalog with 5822 dataset(s) from 351564 asset(s)>
```

This can be a computationally expensive task for larger collections, and in some cases completely unnecessary if we only wish to view the metadata of the collection's entry. 

While a current workaround is to use the catalog's `_entries` attribute to view the entries without loading their DataFrames into memory, this issue could also be circumvented with the creation of an ESMSource class to be used as a driver for Intake-esm collections, such that the underlying DataFrame is not loaded into memory until a dedicated method is called:

```python
In [5]: cat["cmip6_gcs"]
Out[5]: <name: cmip6_gcs>

In [6]: cat["cmip6_gcs"].load()
Out[6]: <pangeo-cmip6 catalog with 5822 dataset(s) from 351564 asset(s)>
```
