### ISSUE TITLE
Dynamically setting parameters

### ISSUE THREAD

**Issue by JPFrancoia** [intake/intake#569]
Hi,

Let's say I have a simple catalog like this:

```yaml
metadata:
  version: 1

sources:
  pizzas:
    description: Awesome pizzas
    driver: csv
    parameters:
      data_dir:
        description: path to data dir
        type: str
    args:
      urlpath: '{{ data_dir }}/pizzas.csv'

  beers:
    description: Awesome beers
    driver: csv
    parameters:
      date:
        description: A beer brand
        type: str
      data_dir:
        description: path to data dir
        type: str
    args:
      urlpath: '{{ data_dir }}/beer_data_{{ date }}.csv'
```

I can load the catalog with:

```python
import intake

catalog = intake.open_catalog('catalog.yaml')
```

Is there a way to set the `data_dir` parameter at the catalog level? Ideally, I would set it only once and it would be applied to all my sources. This needs to be dynamic though, I can't simply set a variable in the yaml file

If this isn't possible, I was wondering if there is a way to iterate over all the sources of the catalog, and check which parameters are defined for each source. The flow would be:

- iterate on each data source
- if data source has a `date` parameter, set the parameter

Is this supported?
