### ISSUE TITLE
Search from metadata from a YAML catalog

### ISSUE THREAD

**Issue by PBrockmann** [intake/intake#599]
Is there a way to search from metadata described in a YAML catalog ?

Let's say I would like to find all sources that have "Patrick" as author ?

```
metadata:
  version: 1
sources:
  example1:
    description: test
    driver: netcdf
    args:
        urlpath: '/thredds/tgcc/store/p529bast/OL2/PROD/refORC22/SIBERIA.MRLC.0.025/SRF/Analyse/SE/SIBERIA.MRLC.0.025_SE_1990_1999_1M_sechiba_history.nc'
    metadata:
        author: 'Patrick'
        ref: 'A journal'
  example2:
    description: test
    driver: netcdf
    args:
        urlpath: '/thredds/tgcc/store/p529bast/OL2/PROD/refORC22/SIBERIA.MRLC.0.025/SRF/Analyse/SE/SIBERIA.MRLC.0.025_SE_2000_2009_1M_sechiba_history.nc'
    metadata:
        author: 'John'
        ref: 'A journal'
```
