### ISSUE TITLE
built in yaml_file_cat driver results in yaml ConstructorError for intake_xarray driver

### ISSUE THREAD

**Issue by JessicaS11** [intake/intake#608]
I've got the following `test_catalog.yml` file:
```
metadata:
  version: 1
name: IS2-hdf5-icepyx-intake-catalog
sources:
  is2_local:
    args:
      path_as_pattern: ATL{product:2}-{datetime:%Y%m%d%H%M%S}-Sample.h5
      urlpath: /Users/jessica/computing/icepyx/test_data/ATL06-20181214041627-Sample.h5
      xarray_kwargs:
        engine: h5netcdf
        group: /gt1l/land_ice_segments
    description: test text here
    driver: !!python/name:intake_xarray.netcdf.NetCDFSource ''
    name: is2_local
    parameters: {}
```

When I try to open the catalog using `intake.open_catalog("test_catalog.yml")`, I get a ConstructorError:
```
ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/name:intake_xarray.netcdf.NetCDFSource'
  in "<unicode string>", line 13, column 13:
        driver: !!python/name:intake_xarray.netc ... 
```

I've been able to trace the error through intake and yaml to [`intake.utils.yaml_load(stream)`](https://github.com/intake/intake/blob/4cf2a7a914825a4b5d7ade710babd22184a3c267/intake/utils.py#L78). `yaml.safe_load()` is [clearly](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation) the best method to use, but obviously an issue if we're trying to use other registered drivers.

I'm not sure if this is technically a bug, or if there's some type of driver registration setup/step I'm missing (since I'm able to import and use the driver to read in data). My naive solution would be to somehow add checks and constructors for other drivers (maybe [here](https://github.com/intake/intake/blob/ded664427ea1d31e23e7521ef4d170df2934d741/intake/utils.py#L60)?). I'm an intake novice, but I'd be happy to contribute towards a solution directly to intake if that's the best spot for it, or at least add some notes to the docs if there's another recommended approach.
