### ISSUE TITLE
Seeking demonstration of derived dataset

### ISSUE THREAD

**Issue by kthyng** [intake/intake#652]
Hi! I'm trying to figure out how to use [derived datasets](https://intake.readthedocs.io/en/latest/transforms.html) from the docs and code and can't put together any code that works using the csv examples. Would it be possible to get one example of code that will run that shows how someone would write one of these, including what to put in what sort of file, what to import, and how to run it? I've tried to parse the docs but just can't wrap my head around it. If so, thank you!

**Comment by teaguesterling** [comment]
Here's a example that I've been playing with that will compute summary stats (using `describe`) for a data frame. It's a bit long winded still. The example usage references the VOTW data used elsewhere in the examples.

```python
# transform_example.py
from intake.source.derived import DataFrameTransform, first


class DescribeDataFrame(DataFrameTransform):
    """
    Computes summary stats on a dataframe
    """
    name = 'describe_dataframe'
    required_params = []
    optional_params = {
        'percentiles': [0.01,0.1,0.25,0.5,0.75,0.9,0.99],
        'include': 'all',
        'exclude': None,
    }

    def __init__(self, 
                 targets,
                 percentiles=(0.01,0.1,0.25,0.5,0.75,0.9,0.99),
                 include='all', 
                 exclude=None, 
                 **kwargs):
        targets = [targets] if isinstance(targets, str) else targets  # we need a list
        # DataFrameTransform uses "transform_kwargs" but we're capturing these in the
        # class instance anding using a method instead
        kwargs.setdefault('target_chooser', first)
        kwargs.setdefault('transform', self.transform)
        kwargs.setdefault('transform_kwargs', {})
        super().__init__(targets=targets, **kwargs)
        self._percentiles = percentiles
        self._include = include
        self._exclude = exclude
        
    def transform(self, df):
        return df.describe(
            percentiles=self._percentiles, 
            include=self._include, 
            exclude=self._exclude
        )
```

```yaml
# derived-catalog.yaml
# Assuming votw-catalog.yaml exists with a source named votw_pandas
metadata:
  version: 1

sources:
  votw_stats:
    description: "Column-level descritive statistics of VOTW data in the Pandas format"
    driver: transform_example.DescribeDataFrame
    args:
      percentiles: [0, 0.25, 0.5, 0.75, 1]
      targets: votw-catalog.yaml:votw_pandas
```

```python
catalog = intake.open_catalog('derived-catalog.yaml')
stats_source = catalog.votw_stats()
stats = stats_source.read()
print(stats.columns)
# Index(['FID', 'Volcano_Number', 'Volcano_Name', 'Primary_Volcano_Type',
#       'Last_Eruption_Year', 'Country', 'Geological_Summary', 'Region',
#       'Subregion', 'Latitude', 'Longitude', 'Elevation', 'Tectonic_Setting',
#       'Geologic_Epoch', 'Evidence_Category', 'Primary_Photo_Link',
#       'Primary_Photo_Caption', 'Primary_Photo_Credit', 'Major_Rock_Type',
#       'GeoLocation'],
#      dtype='object')
print(stats.index)
# Index(['unique', 'count', 'top', 'freq', 'mean', 'std', 'min', '0%', '25%',
#       '50%', '75%', '100%', 'max'],
#      dtype='object')

**Comment by martindurant** [comment]
Thanks for the example, @teaguesterling ! 
I should note that the whole derived datasets idea is somewhat experimental and provides multiple ways to achieve what you want; flexibility at the cost of complexity. There are probably simpler APIs that could be built around it. I suggest you (@kthyng ) also look in the tests for possible usage of the current structures.

**Comment by kthyng** [comment]
@teaguesterling, @martindurant  Thank you! I will try the example here and look at the tests for examples too, next week. I need to have something that runs so that I can build from there but haven't been able to get to that initial point yet. I'll give an update when I hopefully figure it out!

**Comment by teaguesterling** [comment]
> Thanks for the example, @teaguesterling ! I should note that the whole derived datasets idea is somewhat experimental and provides multiple ways to achieve what you want; flexibility at the cost of complexity. There are probably simpler APIs that could be built around it. I suggest you (@kthyng ) also look in the tests for possible usage of the current structures.

I'd love to see more examples as the interface develops. I've been playing with it a good deal and have been finding some areas that I feel are running against the grain of intended usage.

**Comment by martindurant** [comment]
>  running against the grain of intended usage.

This is an open field, would love to see what people have done with it. We didn't have a firm idea of how the feature could be used - but it was inspired by the simplistic transforms available for one-the-fly interactive views of a dataset in `lumen`.

**Comment by aaronspring** [comment]
here my example for a derived dataset of a netcdf file: https://github.com/aaronspring/remote_climate_data/blob/fc1bfd41c9b0e1f14269dba066370f65f95ef3bf/catalogs/ocean/carbon.yaml#L86

**Comment by kthyng** [comment]
I really appreciate all these examples! I will try to put what I have made together into a coherent example too.

First a quick question — is it possible to have the "target" of the transform be simply in memory instead of pointing to a written catalog file? If so what is the syntax for that? Thanks!

**Comment by raybellwaves** [comment]
We have derived datasets in intake-pattern-catalog (https://pypi.org/project/intake-pattern-catalog/)

e.g.
transforms.py:
```
def xarray_to_dask_dataframe(ds: xarray.Dataset) -> dask.DataFrame:
    return ds.to_dask_dataframe()
```

cat.yaml:
```
  ERA5:
    description: ERA5
    driver: pattern_cat
    args:
      urlpath: s3://ERA5/{datetime:%Y%m%d}.zarr
      driver: zarr
      driver_kwargs:
        consolidated: True
      listable: false
  ERA5_dataframe:
    description: ERA5 as a dataframe
    driver: pattern_cat_transform
    args:
      targets:
        - ERA5
      transform: "transforms.xarray_to_dask_dataframe"
```
