### ISSUE TITLE
Unable to pass dict in args

### ISSUE THREAD

**Issue by angus-g** [intake/intake#681]
Perhaps I'm doing something wrong, but it doesn't appear that I can pass a dict through the `args` for a source:

```yaml
sources:
  test:
    driver: zarr
    args:
      urlpath: "reference://"
      storage_options:
        fo: "chunks.json"
        remote_protocol: "s3"
        remote_options:
          client_kwargs:
            endpoint_url: "https://example.com"
```

Attempting to load this catalog gives me `TypeError: unhashable type: 'dict'`, because of the "no duplicates" YAML constructor.
