### ISSUE TITLE
CSV file error: ValueError: Got more bytes so far (>16111) than requested (386)

### ISSUE THREAD

**Issue by kthyng** [intake/intake#701]
Hi! Just ran across this while trying to make an example catalog.

I can read in some data directly with `pandas` fine, like so:

```
import pandas as pd
loc = 'https://opendap.co-ops.nos.noaa.gov/ioos-dif-sos/SOS?service=SOS&request=GetObservation&version=1.0.0&observedProperty=sea_water_speed&direction_of_sea_water_velocity&offering=urn:ioos:station:NOAA.NOS.CO-OPS:COI0513&responseFormat=text/csv&eventTime=2005-07-04T01:08:00Z/2005-07-06T19:38:00Z'
pd.read_csv(loc)
```

but when I set up a basic catalog ("sample_intake.yaml") to do the same thing like this:
```
name: Example

sources:
  COI0513:
    args:
      urlpath: https://opendap.co-ops.nos.noaa.gov/ioos-dif-sos/SOS?service=SOS&request=GetObservation&version=1.0.0&observedProperty=sea_water_speed&direction_of_sea_water_velocity&offering=urn:ioos:station:NOAA.NOS.CO-OPS:COI0513&responseFormat=text/csv&eventTime=2005-07-04T01:08:00Z/2005-07-06T19:38:00Z
    description: ''
    driver: intake.source.csv.CSVSource
    metadata: {}  
```
and call
```
import intake
cat = intake.open_catalog("sample_intake.yaml")
cat['COI0513'].read()
```

I get the error
```
ValueError: Got more bytes so far (>16111) than requested (386)
```

Full trace:
<details>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-25-b354f74017ca> in <module>
----> 1 cat['COI0513'].read()

~/miniconda3/envs/xroms/lib/python3.8/site-packages/intake/source/csv.py in read(self)
    127 
    128     def read(self):
--> 129         self._get_schema()
    130         return self._dataframe.compute()
    131 

~/miniconda3/envs/xroms/lib/python3.8/site-packages/intake/source/csv.py in _get_schema(self)
    113 
    114         if self._dataframe is None:
--> 115             self._open_dataset(urlpath)
    116 
    117         dtypes = self._dataframe._meta.dtypes.to_dict()

~/miniconda3/envs/xroms/lib/python3.8/site-packages/intake/source/csv.py in _open_dataset(self, urlpath)
     92 
     93         if self.pattern is None:
---> 94             self._dataframe = dask.dataframe.read_csv(
     95                 urlpath, storage_options=self._storage_options,
     96                 **self._csv_kwargs)

~/miniconda3/envs/xroms/lib/python3.8/site-packages/dask/dataframe/io/csv.py in read(urlpath, blocksize, lineterminator, compression, sample, enforce, assume_missing, storage_options, include_path_column, **kwargs)
    650         **kwargs,
    651     ):
--> 652         return read_pandas(
    653             reader,
    654             urlpath,

~/miniconda3/envs/xroms/lib/python3.8/site-packages/dask/dataframe/io/csv.py in read_pandas(reader, urlpath, blocksize, lineterminator, compression, sample, enforce, assume_missing, storage_options, include_path_column, **kwargs)
    485         sample = blocksize
    486     b_lineterminator = lineterminator.encode()
--> 487     b_out = read_bytes(
    488         urlpath,
    489         delimiter=b_lineterminator,

~/miniconda3/envs/xroms/lib/python3.8/site-packages/dask/bytes/core.py in read_bytes(urlpath, delimiter, not_zero, blocksize, sample, compression, include_path, **kwargs)
    149                 sample = f.read(sample)
    150             else:
--> 151                 sample_buff = f.read(sample)
    152                 while True:
    153                     new = f.read(sample)

~/miniconda3/envs/xroms/lib/python3.8/site-packages/fsspec/implementations/http.py in read(self, length)
    455         else:
    456             length = min(self.size - self.loc, length)
--> 457         return super().read(length)
    458 
    459     async def async_fetch_all(self):

~/miniconda3/envs/xroms/lib/python3.8/site-packages/fsspec/spec.py in read(self, length)
   1447             # don't even bother calling fetch
   1448             return b""
-> 1449         out = self.cache._fetch(self.loc, self.loc + length)
   1450         self.loc += len(out)
   1451         return out

~/miniconda3/envs/xroms/lib/python3.8/site-packages/fsspec/caching.py in _fetch(self, start, end)
    374         ):
    375             # First read, or extending both before and after
--> 376             self.cache = self.fetcher(start, bend)
    377             self.start = start
    378         elif start < self.start:

~/miniconda3/envs/xroms/lib/python3.8/site-packages/fsspec/asyn.py in wrapper(*args, **kwargs)
     70     def wrapper(*args, **kwargs):
     71         self = obj or args[0]
---> 72         return sync(self.loop, func, *args, **kwargs)
     73 
     74     return wrapper

~/miniconda3/envs/xroms/lib/python3.8/site-packages/fsspec/asyn.py in sync(loop, func, timeout, *args, **kwargs)
     51     event.wait(timeout)
     52     if isinstance(result[0], BaseException):
---> 53         raise result[0]
     54     return result[0]
     55 

~/miniconda3/envs/xroms/lib/python3.8/site-packages/fsspec/asyn.py in _runner(event, coro, result, timeout)
     18         coro = asyncio.wait_for(coro, timeout=timeout)
     19     try:
---> 20         result[0] = await coro
     21     except Exception as ex:
     22         result[0] = ex

~/miniconda3/envs/xroms/lib/python3.8/site-packages/fsspec/implementations/http.py in async_fetch_range(self, start, end)
    517                         cl += len(chunk)
    518                         if cl > end - start:
--> 519                             raise ValueError(
    520                                 "Got more bytes so far (>%i) than requested (%i)"
    521                                 % (cl, end - start)

ValueError: Got more bytes so far (>16111) than requested (386)
</details>

**Comment by martindurant** [comment]
Bizarrely, the server responds to HTTP HEAD with incorrect information
```
import requests
In [27]: requests.head(u).headers
Out[27]: {'Date': 'Mon, 30 Jan 2023 21:55:42 GMT', 'Content-Type': 'application/xml;charset=utf-8', 'Content-Length': '386', 'Connection': 'keep-alive', 'Server': 'nginx/1.22.0', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload'}
```
Note the stated length of 386 - but the data is much longer than this.

Pandas always opens the file in streaming mode, because it doesn't need to care about splitting for dask partitions. Neither does the server accept Range requests, so actually knowing the length is not useful to us at all.

Currently intake uses Dask to load CSV, but I think I will change this. It should be enough to specify 
```
    storage_options:
      block_size: 0
```
for this to work.

**Comment by martindurant** [comment]
> Maybe a way to split up the options would be for .read() to be with pandas and .to_dask to be with dask.

Yes, exactly. This behaviour of using dask for everything has been baked into intake since before I came to project, but should be revisited.

**Comment by kthyng** [comment]
Ah I see. I actually thought you had started the project!

Any thoughts about how to get this catalog to work?

**Comment by martindurant** [comment]
> I actually thought you had started the project

Almost, but not quite.

I have made a small change in fsspec that is correct and helps, but does not solve the problem. You can however do the following

```yaml
  args:
    csv_kwargs:
      blocksize: null
    storage_options:
      block_size: 0
    urlpath: https://opendap.co-ops.nos.noaa.gov/ioos-dif-sos/SOS?service=SOS&request=GetObservation&version=1.0.0&observedProperty=sea_water_speed&direction_of_sea_water_velocity&offering=urn:ioos:station:NOAA.NOS.CO-OPS:COI0513&responseFormat=text/csv&eventTime=2005-07-04T01:08:00Z/2005-07-06T19:38:00Z
  description: ''
  driver: intake.source.csv.CSVSource
  metadata: {}
```
