### ISSUE TITLE
Revising catalog-level GUI

### ISSUE THREAD

**Issue by AlbertDeFusco** [intake/intake#714]
I get weird things when I try to open the GUI on a catalog-of-catalogs.

```yaml
# catalogs.yml
sources:
    weather:
        driver: yaml_file_cat
        args:
            path: https://gist.githubusercontent.com/AlbertDeFusco/60a3d2031f89f1fed1d396bb367fe168/raw/401b29419608abd51985f45a81308bc3f4534410/weather.yaml
```

then in the notebook the gui doesn't appear to work.

<img width="705" alt="Screenshot 2023-02-27 at 23 03 45" src="https://user-images.githubusercontent.com/43654/221759070-3d655bb0-cb89-4c0a-9efc-c1affdb02e47.png">

If instead I swap out [`CatalogGUI`](https://github.com/intake/intake/blob/9d9eebd602fde69ed36bb2e0976d2c27564c05f9/intake/catalog/base.py#L484-L492) for the `interface.gui.GUI`

```python
    @property
    def gui(self):
        if not hasattr(self, "_gui"):
            from ..interface import do_import
            from ..interface.gui import GUI
            do_import()
            self._gui = GUI(self)
        else:
            self._gui.visible = True
        return self._gui
```

I get a much better experience with nested catalogs

<img width="870" alt="Screenshot 2023-02-27 at 23 07 28" src="https://user-images.githubusercontent.com/43654/221759476-ff6f6e13-14ad-44e9-8afc-c1303bc06a42.png">

I am interested in making a PR if you think this is reasonable. Also, is this a good use of `do_import()` or should something else be done to ensure that the panel extension is loaded?
