### ISSUE TITLE
Use the output of a container as input for a catalog source

### ISSUE THREAD

**Issue by wachsylon** [intake/intake#715]
Hi,

sorry if the terms I used in the following are not fully correct according to official definitions.

Lets assume I have catalog `hi` with an entry:
```
sources:
  freva_cmip5_df:
    args:
      base_url: SOLRURL
      core: latest
      qargs:
        rows: '100'
      query: project:cmip5
    driver: intake_solr.source.SOLRTableSource
```

`hi.freva_cmip5_df.read()` returns a DataFrame.  Can I use this DataFrame within another catalog entry which uses a DataFrame as input in the `args` somehow?

In general, can I use the *container* (dont know if that is the correct name) i.e. the output of a source for another intake catalog entry?

Thanks!

**Comment by martindurant** [comment]
Yes you can - please see "derived datasets", also known as [transforms](https://intake.readthedocs.io/en/latest/transforms.html).

**Comment by wachsylon** [comment]
Thanks for the quick response!

However it seems like there is only support for exactly **one** source as an argument, right? I cannot distinguish between different sources in the parameters.

Also, the visibility in the docs is not correct, some yaml parts were hidden. I had to look into the raw file.

**Comment by wachsylon** [comment]
Here is what I mean:
The intake-esm plugin needs one json and one dataframe input. I define those in the sources. Then I need to specify the relevant `transform_kwargs` for the `main_cat` but I do not know how:

```
sources:
  freva_cmip5_df:
    args:
      base_url: URL
      core: latest
      qargs:
        rows: '100'
      query: project:cmip5
    driver: intake_solr.source.SOLRTableSource
  generic_intake_json:
    args:
      urlpath: generic.json
    description: This is an ESM collection for CMIP5 data accessible on the DKRZ's
    driver:
    - json
  main_cat:
    driver: intake.source.derived.GenericTransform
    args:
      targets:
        - freva_cmip5_df
        - generic_intake_json
      transform: intake.open_esm_datastore
      transform_kwargs:
        esmcol_obj: freva_cmip5_df
        esmcol_data: generic_intake_json
```
