### ISSUE TITLE
Can I have a defined plot for a transform dataset?

### ISSUE THREAD

**Issue by kthyng** [intake/intake#724]
I'm defining a catalog in which there is a "base" csv data (`ctd_base` below) and a dataset that is a transformed/derived version of `ctd_base` called `ctd`, which does some processing to produce a more usable dataset. I would like to have a plot available for source `ctd` — is there a way to do this? Below I'm showing a version of what I've tried but haven't been able to get it to work when I call `cat.ctd.plot.example()` with the error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[18], line 1
----> 1 cat["ctd"].plot.example()

File ~/miniconda3/envs/ciofs/lib/python3.11/site-packages/hvplot/plotting/core.py:92, in hvPlotBase.__call__(self, x, y, kind, **kwds)
     89         plot = self._get_converter(x, y, kind, **kwds)(kind, x, y)
     90         return pn.panel(plot, **panel_dict)
---> 92 return self._get_converter(x, y, kind, **kwds)(kind, x, y)

File ~/miniconda3/envs/ciofs/lib/python3.11/site-packages/hvplot/plotting/core.py:99, in hvPlotBase._get_converter(self, x, y, kind, **kwds)
     97 y = y or params.pop("y", None)
     98 kind = kind or params.pop("kind", None)
---> 99 return HoloViewsConverter(self._data, x, y, kind=kind, **params)

File ~/miniconda3/envs/ciofs/lib/python3.11/site-packages/hvplot/converter.py:389, in HoloViewsConverter.__init__(self, data, x, y, kind, by, use_index, group_label, value_label, backlog, persist, use_dask, crs, fields, groupby, dynamic, grid, legend, rot, title, xlim, ylim, clim, symmetric, logx, logy, loglog, hover, subplots, label, invert, stacked, colorbar, datashade, rasterize, row, col, debug, framewise, aggregator, projection, global_extent, geo, precompute, flip_xaxis, flip_yaxis, dynspread, hover_cols, x_sampling, y_sampling, project, tools, attr_labels, coastline, tiles, sort_date, check_symmetric_max, transforms, stream, cnorm, features, rescale_discrete_levels, **kwds)
    387 self.value_label = value_label
    388 self.label = label
--> 389 self._process_data(
    390     kind, data, x, y, by, groupby, row, col, use_dask,
    391     persist, backlog, label, group_label, value_label,
    392     hover_cols, attr_labels, transforms, stream, kwds
    393 )
    395 self.dynamic = dynamic
    396 self.geo = any([geo, crs, global_extent, projection, project, coastline, features])

File ~/miniconda3/envs/ciofs/lib/python3.11/site-packages/hvplot/converter.py:800, in HoloViewsConverter._process_data(self, kind, data, x, y, by, groupby, row, col, use_dask, persist, backlog, label, group_label, value_label, hover_cols, attr_labels, transforms, stream, kwds)
    798     self.data = data
    799 else:
--> 800     raise ValueError('Supplied data type %s not understood' % type(data).__name__)
    802 if stream is not None:
    803     if streaming:

ValueError: Supplied data type DataFrameTransform not understood
```

CATALOG:

```

name: ctd
description: CTD

sources:
  ctd_base:
    description: Base
    driver: csv
    args:
      urlpath: /Users/kthyng/projects/ciofs-hindcast-report/ciofs_hindcast_report/inputs/data/CTD_KBNERR_301933/301933.csv

  ctd:
    description: CTD
    driver: process.DataFrameTransform
    args:
      targets:
        - ctd_base
      transform: "process.ctd"
      transform_kwargs:
        station: kacbcwq
    metadata:
      plots:
        example:
          kind: line
          x: DateTimeStamp
          y: Temp
          width: 800
          height: 600
```

Also `process.DataFrameTransform` is the same as what is provided in `intake`, and `process.ctd` runs some stuff on the DataFrame.

Thanks for any help!

**Comment by martindurant** [comment]
Is the output of source "ctd" (the result of .read() ) also a dataframe?

**Comment by martindurant** [comment]
I tried the following
Catalog
```yaml
name: ctd
description: CTD

sources:
  ctd_base:
    description: Base
    driver: csv
    args:
      urlpath: data.csv

  ctd:
    description: CTD
    driver: intake.source.derived.DataFrameTransform
    args:
      targets:
        - ctd_base
      transform: "toolz.identity"
      transform_kwargs: {}
    metadata:
      plots:
        example:
          kind: line
```

data.csv
```csv
a,b
0,1
0.1, 1.1
```

and `cat.ctd.plot()` or `cat.ctd.plot.example()` both did run successfully.
