### ISSUE TITLE
Is it possible to specify a Python function as `args` in a YAMLFileCatalog?

### ISSUE THREAD

**Issue by dougiesquire** [intake/intake#725]
I'd like to create a YAMLFileCatalog that includes a source with an argument that is a Python function. Is there a way to do this?

An example using a CSV source:
```python
import ast
import intake
import pandas

# Create the source data
data = {
    "col0": [["a","b"], ["c","d","e"]], 
    "col1": [0, 1]
}
pandas.DataFrame(data).to_csv("test.csv", index=False)

# Open using intake with converter function
cat = intake.open_csv("test.csv", csv_kwargs={"converters": {"col0": ast.literal_eval}})
cat.read() # works

# Can we write a YAML catalog with the converter function specified in args?
with open("test.yaml", "w") as f:
    f.write(cat.yaml())
    
# It seems not (this fails)
intake.open_catalog("test.yaml")
```

The contents of `test.yaml` look like this:

```yaml
sources:
  csv:
    args:
      csv_kwargs:
        converters:
          col0: !!python/name:ast.literal_eval ''
      urlpath: test.csv
    description: ''
    driver: intake.source.csv.CSVSource
    metadata: {}
```
```
