### ISSUE TITLE
Unable to use user parameters with sources in data package

### ISSUE THREAD

**Issue by dougiesquire** [intake/intake#740]
I seem to be unable to specify user parameters on data sources in a data package.

As a reproducible example, I've created a very simple intake data package [here](https://github.com/dougiesquire/intake_data_package) using an example YAML catalog [taken from the intake docs](https://intake.readthedocs.io/en/latest/catalog.html#templating-parameters):

```yaml
sources:
  variabledefault:
    description: "This entry leads to an example csv file in the user's home directory by default, but the user can pass root='somepath' to override that."
    driver: csv
    args:
      urlpath: "{{root}}/example.csv"
    parameters:
      root:
        description: "root path"
        type: str
        default: "env(HOME)"
```

I register the `variabledefault` source as an entry in `intake.cat` called `mydata`.

The following then works as expected and templates the default value for `root`:

```python
>>> import intake
>>> intake.cat.mydata
sources:
  variabledefault:
    args:
      urlpath: /home/example.csv
    description: This entry leads to an example csv file in the user's home directory
      by default, but the user can pass root='somepath' to override that.
    driver: intake.source.csv.CSVSource
    metadata:
      catalog_dir: /home/intake_data_package/package/
```

However, trying to pass a new `root` as a user parameter returns a `TypeError`:

```python
>>> intake.cat.mydata(root="foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../intake/source/base.py", line 395, in configure_new
    obj = self._entry(**kw)
          ^^^^^^^^^^^^^^^^^
  File "/.../intake/catalog/entry.py", line 79, in __call__
    s = self.get(**kwargs)
        ^^^^^^^^^^^^^^^^^^
TypeError: EntrypointEntry.get() got an unexpected keyword argument 'root'
```

Is this something that could be made to work? Apologies in advance if this is user error.
