### ISSUE TITLE
Best way to create intake catalog for kerchunked dataset?

### ISSUE THREAD

**Issue by rsignell** [intake/intake#839]
I have Python code that opens kerchunk-generated Parquet references successfully:
``` python
import fsspec
import xarray as xr

combined_parquet_aws = 's3://esip/rsignell/hycom.parq'
so = dict(anon=True, skip_instance_cache=True)    # data stored on AWS Open Data S3
to = dict(anon=True, skip_instance_cache=True,    # refs stored on OSN 
          client_kwargs={'endpoint_url': 'https://ncsa.osn.xsede.org'})

ds = xr.open_dataset(combined_parquet_aws, engine='kerchunk', chunks={},
                    backend_kwargs=dict(storage_options=dict(target_options=to,
                    remote_protocol='s3', lazy=True, remote_options=so)))
```

There doesn't seem to be an `intake.open_kerchunk` method, so what is the best way to programmatically create the Intake catalog item for this dataset?

**Comment by martindurant** [comment]
Surprising, this does *just work*:
```python
In [24]: ds = xr.open_dataset(combined_parquet_aws, engine='kerchunk', chunks={},
    ...:                     backend_kwargs=dict(storage_options=dict(target_options=to,
    ...:                                         remote_protocol='s3', lazy=True, remote_options=so)))

In [25]: reader = intake.reader_from_call(_i24, join_lines=True)

In [27]: reader.pprint()
{'kwargs': {'engine': 'kerchunk',
            'chunks': {},
            'backend_kwargs': {'storage_options': {'target_options': {'anon': True,
                                                                      'skip_instance_cache': True,
                                                                      'client_kwargs': {'endpoint_url': 'https://ncsa.osn.xsede.org'}},
                                                   'remote_protocol': 's3',
                                                   'lazy': True,
                                                   'remote_options': {'anon': True,
                                                                      'skip_instance_cache': True}}},
            'args': [{'url': 's3://esip/rsignell/hycom.parq',
                      'storage_options': None,
                      'metadata': {}}]},
 'metadata': {}}

In [28]: reader.read()
Out[28]:
<xarray.Dataset>
Dimensions:            (depth: 40, lat: 3251, lon: 4500, time: 63341)
Coordinates:
  * depth              (depth) float64 0.0 2.0 4.0 6.0 ... 3e+03 4e+03 5e+03
  * lat                (lat) float64 -80.0 -79.96 -79.92 ... 89.92 89.96 90.0
  * lon                (lon) float64 -180.0 -179.9 -179.8 ... 179.8 179.8 179.9
  * time               (time) datetime64[ns] 1994-01-01T12:00:00 ... 2015-12-...
Data variables:
    salinity           (time, depth, lat, lon) float32 dask.array<chunksize=(1, 1, 3251, 4500), meta=np.ndarray>
    salinity_bottom    (time, lat, lon) float32 dask.array<chunksize=(1, 3251, 4500), meta=np.ndarray>
    surf_el            (time, lat, lon) float32 dask.array<chunksize=(1, 3251, 4500), meta=np.ndarray>
    water_temp         (time, depth, lat, lon) float32 dask.array<chunksize=(1, 1, 3251, 4500), meta=np.ndarray>
    water_temp_bottom  (time, lat, lon) float32 dask.array<chunksize=(1, 3251, 4500), meta=np.ndarray>
    water_u            (time, depth, lat, lon) float32 dask.array<chunksize=(1, 1, 3251, 4500), meta=np.ndarray>
    water_u_bottom     (time, lat, lon) float32 dask.array<chunksize=(1, 3251, 4500), meta=np.ndarray>
    water_v            (time, depth, lat, lon) float32 dask.array<chunksize=(1, 1, 3251, 4500), meta=np.ndarray>
    water_v_bottom     (time, lat, lon) float32 dask.array<chunksize=(1, 3251, 4500), meta=np.ndarray>
Attributes:
    Conventions:               CF-1.6 NAVO_netcdf_v1.1
    classification_authority:  not applicable
    classification_level:      UNCLASSIFIED
    distribution_statement:    Approved for public release. Distribution unli...
    downgrade_date:            not applicable
    field_type:                instantaneous
    history:                   archv2ncdf3z
    institution:               Naval Oceanographic Office
    source:                    HYCOM archive file
```

You may notice, however, that there is no "data" component here, everything just became kw/args. That's because the URL doesn't look like zarr, and I have neglected to make a kerchunk specific datatype. In fact, I'm not sure whether kerchunk is just a special case of zarr or not (you can in theory have kerchunk reference sets that evaluate to filesystems containing other stuff, we just don't happen to have any). 

Side note: `'skip_instance_cache': True` should only ever be needed during development, not for general use. Actually, you would tend to use it on the outer ReferenceFS anyway, not on the two S3 filesystems it uses internally.

**Comment by rsignell** [comment]
@martindurant , Cool!   What is that `_i24` var though?
Or even better, post the entire notebook as a gist or something!
Thanks!

**Comment by martindurant** [comment]
> What is that _i24 var

That's an ipython/juypter convenience "the text of input number 24". You could have used 
```python
"""
ds = xr.open_dataset(combined_parquet_aws, engine='kerchunk', chunks={},
              backend_kwargs=dict(storage_options=dict(target_options=to,
                                   remote_protocol='s3', lazy=True, remote_options=so)))
"""
```
(but the various contained variables like combined_parquet_aws do need to be defined, of course)

I don't think there's a way to get this "last command I wrote" in the standard python interpreter or in a script.

**Comment by rsignell** [comment]
Ah, okay, I did not know about that convenience method to get the inputs of a cell as a string!

I struggled a bit to reproduce this until I realized that I needed to use intake master branch from github instead of the most recent release (2.0.5  from May).   What do you think about new release of intake?

Finally, I'm trying to write the intake catalog to yaml, but this:
``` python
source = intake.reader_from_call(_i5, join_lines=True)

description = "HYCOM Datasets"
catalog = {'metadata': {'version': 2, 'description': description}, 'sources': source}

with open('hycom_catalog.yml', 'w') as f:
    yaml.dump(catalog, f)
```
produces:
```
!!python/object:intake.readers.readers.XArrayDatasetReader
kwargs:
  args: !!python/tuple
  - !!python/object:intake.readers.datatypes.Parquet
    metadata: {}
    storage_options: null
    url: s3://esip/rsignell/hycom.parq
  backend_kwargs:
    storage_options:
      lazy: true
      remote_options:
        anon: true
      remote_protocol: s3
      target_options:
        anon: true
        client_kwargs:
          endpoint_url: https://ncsa.osn.xsede.org
  chunks: {}
  engine: kerchunk
metadata: {}
```

**Comment by martindurant** [comment]
The catalog has a method: [`to_yaml_file`](https://intake.readthedocs.io/en/latest/api2.html#intake.readers.entry.Catalog.to_yaml_file)

**Comment by rsignell** [comment]
Martin, you mean the reader object has a method `to_yaml_file`, right?   

When I try:
```
source = intake.reader_from_call(_i5, join_lines=True)

source.to_yaml_file('hycom.yaml')
```
I don't get errors, but also don't get any file written.  I get the output:
![image](https://github.com/user-attachments/assets/795e2517-56df-4462-ba5c-214e596cd684)

I then tried converting the `intake.readers.readers.XArrayDatasetReader` object `source` to a dict and adding it to a catalog thusly:
``` python
import yaml
description = "HYCOM Datasets"
catalog = {'metadata': {'version': 2, 'description': description}, 
           'sources': source.to_dict()}

with open('hycom_catalog.yml', 'w') as f:
    yaml.dump(catalog, f)

```
which creates:
``` yaml
metadata:
  description: HYCOM Datasets
  version: 2
sources:
  kwargs:
    args:
    - metadata: {}
      storage_options: null
      url: s3://esip/rsignell/hycom.parq
    backend_kwargs:
      storage_options:
        lazy: true
        remote_options:
          anon: true
        remote_protocol: s3
        target_options:
          anon: true
          client_kwargs:
            endpoint_url: https://ncsa.osn.xsede.org
    chunks: {}
    engine: kerchunk
  metadata: {}
```
