### ISSUE TITLE
Codifing remote excel file in YAML

### ISSUE THREAD

**Issue by pgierz** [intake/intake#863]
Hi there,

I'm trying to codify a remote excel file into a catalog and am getting stuck with how to write down the reader/driver combination. I think a page in the documentation with several examples would be very useful.

So far I have something like this:
```yaml
sources:
  SSPS_CO2:
    args: 
      urlpath: "zip://SUPPLEMENT_DataTables_Meinshausen_6May2020.xlsx::https://gmd.copernicus.org/articles/13/3571/2020/gmd-13-3571-2020-supplement.zip"
      sheet_name: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
      skiprows: 11
      usecols="A:B"
      names: ["Year", "CO2"]
      index_col: "Year"
    driver: csv
    reader: excel
```

Note that this works fine in Python:
```python
import pandas as pd
dfs = pd.read_excel("zip://SUPPLEMENT_DataTables_Meinshausen_6May2020.xlsx::https://gmd.copernicus.org/articles/13/3571/2020/gmd-13-3571-2020-supplement.zip", 
                    sheet_name=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
                    skiprows=11, usecols="A:B", names=["Year", "CO2"], index_col="Year")
```

What am I missing here?
